#=============================================================================
# basic.toml --- basic configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    #autocomplete_method = 'Completor'
    colorscheme = 'SpaceVim'
    colorscheme_bg = 'dark'
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = false
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = 'arrow'
    statusline_iseparator = 'bar'
    buffer_index_type = 4
    windows_index_type = 3
    enable_tabline_filetype_icon = false
    enable_statusline_mode = false
    statusline_unicode_symbols = false
    buffer_index_type = 0
    statusline_left_sections = [
      'winnr',
      'filename',
      'fileformat'
    ]
    statusline_right_sections = [
      'cursorpos',
      'percentage',
      'date',
      'time',
      'battery status'
    ]
    # Enable vim compatible mode, avoid changing origin vim key bindings
    vimcompatible = false
    bootstrap_before = 'myspacevim#before'
    bootstrap_after = 'myspacevim#after'
    escape_key_binding = 'jj'

# Enable autocomplete layer
# [[layers]]
# name = 'autocomplete'
# auto_completion_return_key_behavior = 'complete'
# auto_completion_tab_key_behavior = 'cycle'

[[layers]]
  name = 'colorscheme'

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 30

# [[layers]]
# name = 'lang#python'
# enable_typeinfo = true

[[layers]]
  name = 'lang#rust'

[[layers]]
  name = 'lang#c'

[[layers]]
  name = 'test'
  [layers.override_confg]
  python_runner = 'pytest'

[[custom_plugins]]
name = 'dbeniamine/cheat.sh-vim'
merged = 0

[[custom_plugins]]
name = 'neoclide/coc.nvim'

